var firstname="Adisha";
var lastname="Nayak";
var fullname= firstname.concat(lastname);
console.log(fullname);
var sqroot= Math.sqrt(81);
console.log(sqroot);
var maximum_number = Math.max(45,4);
console.log(maximum_number);
var minimum_number = Math.min(67,98);
console.log(minimum_number);
var powerM = Math.pow(9,9);
console.log(powerM);